forum/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.list_topic, name='feed'),
    url(r'^ask/',views.create_topic,name='ask'),
    url(r'detail/(?P<pk>\d+)',views.detail_topic, name='detail'),
    url(r'^answers/(?P<pk>\d+)/correct',views.reply_correct,name='reply_correct'),
    url(r'^answers/(?P<pk>\d+)/incorrect',views.reply_incorrect,name='reply_incorrect'),
]

olimpo_andressa/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^accounts/', include('accounts.urls',namespace='accounts')),
    url(r'^',include('forum.urls', namespace='forum')),
    url(r'^admin/', admin.site.urls),
]

forum/models.py
from django.db import models
from accounts.models import User

class Topic(models.Model):
    title =  models.CharField('Título',max_length = 150)
    body = models.TextField('Mensagem')
    author  = models.ForeignKey(User, verbose_name ='Autor',related_name='topic')
    views = models.IntegerField('Visualizações',blank=True, default=0)
    answers = models.IntegerField('Respostas',blank=True, default=0)
    created = models.DateTimeField('Criado em',auto_now_add = True)
    update = models.DateTimeField('Atualizado em',auto_now=True)

    def __str__(self):
        return self.title

    class  Meta:
        verbose_name = 'Tópico'
        verbose_name_plural = 'Tópicos'
        ordering = ['-update']

class reply(models.Model):
    topic = models.ForeignKey(Topic, verbose_name='Tópico',related_name='replies')
    reply = models.TextField('Mensagem')
    author  = models.ForeignKey(User, verbose_name ='Autor',related_name='replies')
    correct = models.BooleanField('Correta?',blank=True,default=False)
    created = models.DateTimeField('Criado em',auto_now_add = True)
    update = models.DateTimeField('Atualizado em',auto_now=True)

    def __str__(self):
        return self.reply[:100]

    class  Meta:
        verbose_name = 'Resposta'
        verbose_name_plural = 'Respostas'
        ordering = ['correct','created']

def post_save_reply(created,instance,**kwargs):
    instance.topic.answers = instance.topic.replies.count()
    instance.topic.save()
    if instance.correct:
        instance.topic.replies.exclude(pk=instance.pk).update(correct="False")

def post_delete_reply(instance,**kwargs):
    instance.topic.answers = instance.topic.replies.count()

models.signals.post_save.connect(
    post_save_reply,sender = reply,dispatch_uid = 'post_save_reply'
)


models.signals.post_delete.connect(
    post_delete_reply, sender = reply,dispatch_uid = 'post_delete_reply'
)

# Create your models here.

forum/forms.py
from django  import forms
from .models import reply

class ReplyForm (forms.ModelForm):
    class Meta:
        model  = reply
        fields = ['reply']

forum/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import CreateView,ListView,DetailView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from  .models  import Topic,reply
from  django.core.urlresolvers import reverse_lazy
from .forms import ReplyForm


class CreateTopicView(CreateView):
    model = Topic
    fields  = ['title','body']
    template_name = 'ask.html'
    success_url = reverse_lazy('forum:feed')

    def form_valid(self,form):
        form.instance.author = self.request.user
        return super(CreateTopicView,self).form_valid(form)


class ListTopicView(ListView):
    paginate_by = 5
    model = Topic
    template_name = 'feed.html'
    context_object_name = 'topics'

class DetailTopicView(DetailView):
    model  = Topic
    template_name = 'show.html'
    context_object_name = 'topic'

    def get(self,request,*args,**kwargs):
        response = super(DetailView,self).get(request,*args,**kwargs)
        if  self.request.user.is_authenticated() and \
            (self.object.author != self.request.user):
                self.object.views = self.object.views + 1
                self.object.save()
        return response

    def  get_context_data(self,**kwargs):
        context = super(DetailTopicView,self).get_context_data(**kwargs)
        context['form'] = ReplyForm(self.request.POST or None)
        return context

    def post(self,request,*args,**kwargs):
        if not self.request.user.is_authenticated:
            return redirect('accounts:login')
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        form = context['form']
        if form.is_valid():
            reply = form.save(commit = False)
            reply.topic = self.object
            reply.author  = self.request.user
            reply.save()
            context['form'] = ReplyForm()
        return self.render_to_response(context)

class ReplyCorrectView(View):
    correct = True
    def get(self,resquest,pk):
        r = get_object_or_404(reply, pk=pk)
        r.correct = self.correct
        r.save()
        return redirect(reverse_lazy('forum:detail',kwargs={'pk':r.topic.pk}))



detail_topic = DetailTopicView.as_view()
list_topic =  ListTopicView.as_view()
create_topic = CreateTopicView.as_view()
reply_correct = ReplyCorrectView.as_view()
reply_incorrect = ReplyCorrectView.as_view(correct=False)

forum/templates/ask.html
{% extends 'nav.html' %}
{% load widget_tweaks %}
{% block 'content' %}

<div class="ui clearing segment">

                <form class="ui form"  method="POST">
                  {% csrf_token %}

                  <div class="field">

                    <label for="form.body.auto_id">{{form.title.label}}</label>
                  {% render_field form.title  placeholder="Qual sua  dúvida?" %}
                  {% for  error in form.title.erros %}
                    <div class="ui erroor  message">
                        <div class="header">Atenção!</div>
                          <p>{{error}}</p>

                    </div>
                  {% endfor %}
                </div>

                    <div class="field">

                      <label for="form.body.auto_id">{{form.body.label}}</label>
                    {% render_field form.body class="expand" rows="2" placeholder="Conte-me mais" %}
                    {% for  error in form.body.erros %}
                      <div class="ui erroor  message">
                          <div class="header">Atenção!</div>
                            <p>{{error}}</p>

                      </div>
                    {% endfor %}


                    </div>

                    <div class="ui error message"></div>

                    <button type="submit"  class="ui animated right floated primary submit button" tabindex="0">

                        <div class="visible content">Perguntar</div>

                        <div class="hidden content">

                            <i class="add icon"></i>

                        </div>

                    </button>

                </form>

            </div>

{% endblock %}

forum/templates/feed.html
{% extends "nav.html" %}
{% load static %}
{% block 'content' %}


<div class="ui segments">

    <header class="ui clearing segment">

        <div class="ui right floated floating labeled icon dropdown button">

            <i class="filter icon"></i>

            <span class="text">Filtros</span>

            <div class="menu">

                <div class="header">Filtrar por</div>

                <div class="divider"></div>

                <div class="item">

                    Mais Recentes

                </div>

                <div class="item">

                    Mais Visualizados

                </div>

                <div class="item">

                    Meus Tópicos

                </div>

            </div>

        </div>

    </header>

    <div class="ui segment">

        <div class="ui large feed">

          {% for topic in topics %}



      <div class="event">
              <div class="label">
                {% with 'imgs/avatars/'|add:topic.author.avatar|add:'.png' as avatar %}

                <img src="{% static avatar %}">

                {% endwith %}

                </div>

                <div class="content">

                    <div class="summary">

                        <a class="user">{{topic.author}}</a> fez uma <a href="{% url 'forum:detail' topic.pk %}">pergunta</a>

                        <div class="date">à {{topic.created|timesince}} atrás</div>

                    </div>

                    <div class="extra text">

                        {{topic.title}}

                    </div>

                    <div class="meta">

                        <a>

                        <i class="comments icon"></i>

                      {{topic.answers}}  respostas

                    </a>
                    <a>

                    <i class="eye icon"></i>

                  {{topic.views}}  visualizações

                </a>
                    </div>

                </div>

            </div>

{% endfor %}

        </div>

    </div>

    <footer class="ui clearing segment">
        <div class="ui right floated buttons">
            {% if page_obj.has_previous %}
              <a href="?page{{page_obj.previous_page_number}}" class="ui icon button">
                <i class="left chevron icon"></i>
              </a>
            {% endif %}

            {% for page in paginator.page_range  %}
              <a href="?page={{page}}"  class="ui button">
                {{page}}
              </a>
            {% endfor %}

            {% if page_obj.has_next %}
            <a href="?page{{page_obj.next_page_number}}"  class="ui icon button">
              <i class="right chevron icon"></i>
            </a>
            {% endif %}
        </div>
    </footer>
</div>

{% endblock %}

forum/templates/show.html
{% extends "nav.html" %}

{% load widget_tweaks %}

{% load static %}

{% block 'content' %}



  <div class="ui clearing segment">

    <header class="ui padded segment">

      <a href="{% url 'forum:feed' %}" class="ui animated fade violet button" tabindex="0">

        <div class="visible content">Feed</div>

        <div class="hidden content">

          <i class="rss icon"></i>

        </div>

      </a>

    </header>



<div class="ui large feed">

    <div class="event">

      <div class="label">

        {% with 'imgs/avatars/'|add:topic.author.avatar|add:'.png' as avatar %}

        <img src="{% static avatar %}">

        {% endwith %}

      </div>

      <div class="content">

        <div class="summary">

          <a class="user">{{topic.author}}</a> fez uma <a href="{% url 'forum:detail' topic.pk %}">pergunta</a>

          <div class="date">à {{topic.created|timesince}} atrás</div>

        </div>

        <div class="extra text">

          {{topic.title}}

          <div class="ui segment">

            {{topic.body|linebreaks}}

          </div>

        </div>

      </div>

    </div>

  </div>



  <div class="ui large feed">

    {% for reply in topic.replies.all  %}

      <div class="event">

        <div class="label">

          {% with 'imgs/avatars/'|add:reply.author.avatar|add:'.png' as avatar %}

          <img src="{% static avatar %}">

          {% endwith %}

        </div>

        <div class="content">

          <div class="summary">

            <a class="user">{{reply.author}}</a> Respondeu:</a>

            <div class="date">à {{reply.created|timesince}} atrás</div>

          </div>

          <div class="extra text">

            {{reply.reply|linebreaks}}

          </div>

        </div>

        {% if reply.correct %}
          {% if topic.author == user %}
            <a href="{% url 'forum:reply_incorrect' reply.pk %}">Cancelar resposta correta</a>
          {% endif %}
          <label>Resposta Indicada pelo Autor</label>
        {% elif topic.author == user %}
          <a href="{% url 'forum:reply_correct' reply.pk %}">Resposta Correta</a>
        {% endif %}

      </div>

      {% empty %}

      <h1>Sem respostas até o momento :'(</h1>

      {% endfor %}

    </div>
<form class="ui  form"  method="post">
  {% csrf_token %}
  {{form.reply.label_tag}}
  {% render_field form.reply classs="expand" rows="2" %}
  <button type="submit" class="ui right floated animated button green" tabindex="0">

      <div class="visible content">Enviar</div>

      <div class="hidden content">

        <i class="check icon"></i>

      </div>

    </button>
</form>


</header>

</div>



{% endblock %}