accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views

urlpatterns = [
    url(r'^login/$', login, {'template_name':'login.html'},name='login'),
    url(r'^logout/$', logout,{'next_page':'accounts:login'}, name='logout'),
    url(r'^signin/$', views.signin, name = 'signin'),
    url(r'^profile/$',views.profile,name='profile'),
    url(r'^edit/profile$',views.edit_profile,name='edit_profile'),
]

forum/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.list_topic, name='feed'),
    url(r'^ask/',views.create_topic,name='ask'),
    url(r'detail/(?P<pk>\d+)',views.detail_topic, name='detail'),
    url(r'^answers/(?P<pk>\d+)/correct',views.reply_correct,name='reply_correct'),
    url(r'^answers/(?P<pk>\d+)/incorrect',views.reply_incorrect,name='reply_incorrect'),
]

olimpo_andressa/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^accounts/', include('accounts.urls',namespace='accounts')),
    url(r'^',include('forum.urls', namespace='forum')),
    url(r'^admin/', admin.site.urls),
]

accounts/models.py
from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, UserManager,PermissionsMixin
import re

class User(AbstractBaseUser,PermissionsMixin):
    DEFAULT = 'default'
    ELYSE = 'elyse'
    EVE = 'eve'
    KRISTY = 'kristy'
    LENA = 'lena'
    MARK = 'mark'
    MATTHEW = 'matthew'
    MOLLY = 'molly'
    RACHEL = 'rachel'

    AVATARS = (
            (DEFAULT,'default'),
            (ELYSE,'elyse'),
            (EVE,'eve'),
            (KRISTY,'kristy'),
            (LENA,'lena'),
            (MARK,'mark'),
            (MATTHEW,'matthew'),
            (MOLLY,'molly'),
            (RACHEL,'rachel')

        )

    username = models.CharField('Usuário', max_length=25, unique=True, validators=[
        validators.RegexValidator(
            re.compile('^[\w.@+-]+$'),
            'Informe o nome de usuário válido!',
            'Este valor deve conter apenas letras e os caracteres: @/ ./+/-/_',
            'invalid'
        )
    ],help_text='Um nome curto que será usado para identificá-lo de forma única'
    )
    name = models.CharField('Nome',max_length=100)
    email= models.EmailField('Email',unique=True)
    avatar = models.CharField('Avatar', max_length=50,choices=AVATARS, default=DEFAULT)
    is_staff = models.BooleanField('Equipe', default=False)
    is_active =  models.BooleanField('Ativo', default=True)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add = True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

class Meta:
    verbose_name = 'Usuário'
    verbose_name_plural = 'Usuários'

def __str__(self):
    return self.name or self.username


def get_full_name(self):
    return str(self)

def get_short_name(self):
    return str(self).split(" ")[0]

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import User

class UserCreationForm(UserCreationForm):
    """docstring for ."""
    class Meta:
        model = User
        fields = ['username','email']

#para criar pelo django admin
class UserAdminForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','email','name','is_active','is_staff']
        

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView,DetailView,UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import User
from .forms import UserCreationForm
from django.core.urlresolvers import reverse_lazy

class Profile(LoginRequiredMixin,DetailView):
    model = User
    template_name = 'profile.html'

    def get_object(self):
        return self.request.user

class CreateUserView(CreateView):
    model = User
    template_name = 'new.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('accounts:login')

class EditProfileView(LoginRequiredMixin,UpdateView):
    model = User
    template_name = 'edit.html'
    fields = ['username','name','email','avatar']
    success_url = reverse_lazy('accounts:profile')

    def get_object(self):
        return self.request.user

    def get_context_data(self,**kwargs):
        context = super(EditProfileView,self).get_context_data(**kwargs)
        context['avatars'] = ['default','elyse','eve','kristy','lena','mark','matthew','molly','rachel']
        return context

edit_profile = EditProfileView.as_view()
profile = Profile.as_view()
signin = CreateUserView.as_view()

accounts/templates/edit.html
{% extends 'nav.html' %}
{% load widget_tweaks %}
{% load static %}

{% block 'content' %}

<div class="ui segments">
  <header class="ui clearing segment">
      <button class="ui right floated yellow button">
        Editar perfil
      </button>
  </header>

<div class="ui segment">
  <div class="ui large feed">
    <form class="ui form" method="post">
      {% csrf_token %}
  <div class="field">

<label for="{{form.username.auto_id}}" >{{form.username.label}}</label>
  <div class="ui left icon input">
    {% render_field form.username %}
    <i class="user icon"></i>
  </div>

  {% for error in form.username.errors %}
  <div class="ui error message">
    <div class="header">Atenção!</div>
      <p>{{error}}</p>
    </div>

  {% endfor %}


  <div class="field">
    <label for="{{form.name.auto_id}}" >{{form.name.label}}</label>

            <div class="ui left icon input">

              {% if user.name %}

              {% render_field form.name %}

              {% else %}

              {% render_field form.name placeholder="Queremos tratar você da melhor forma, informe seu nome" %}

              {% endif %}

              <i class="user icon"></i>

            </div>

            {% for error in form.name.errors %}

            <div class="ui error message">

              <div class="header">Atenção!</div>

              <p>{{error}}</p>

            </div>

            {% endfor %}



            <div class="field">

              <label for="{{form.email.auto_id}}" >{{form.email.label}}</label>

              <div class="ui left icon input">

                {% render_field form.email %}

                <i class="envelope icon"></i>

              </div>

              {% for error in form.email.errors %}

              <div class="ui error message">

                <div class="header">Atenção!</div>

                <p>{{error}}</p>

              </div>

              {% endfor %}



              <div class="field">

                <label for="{{form.avatar.auto_id}}" >{{form.avatar.label}}</label>

                <div class="ui left icon input">



                  <div class="ui floating labeled icon dropdown button">

                    <input type="hidden" name="avatar">

                    <i class="photo icon"></i>

                    <span class="text">Selecionar avatar</span>

                    <div class="menu">



                      {% for avatar in avatars %}

                        <div class="item" data-value="{{avatar}}">

                          {% with 'imgs/avatars/'|add:avatar|add:'.png' as path %}

                          <img class="ui avatar image" src="{% static path %}">

                          {% endwith %} {{avatar}}

                        </div>

                      {% endfor %}



                    </div>

                  </div>

                </div>



              </div>

              {% for error in form.avatar.errors %}

              <div class="ui error message">

                <div class="header">Atenção!</div>

                <p>{{error}}</p>

              </div>



              {% endfor %}





              <button type="submit" class="ui animated button green" tabindex="0">

                <div class="visible content">Atualizar</div>

                <div class="hidden content">

                  <i class="check icon"></i>

                </div>

              </button>

            </form>



          </div>

          <div>

          </div>

{% endblock %}

accounts/templates/login.html
{% extends 'imports.html' %}
{% load widget_tweaks %}

{% block 'nav' %}
<main>
<div class="ui centered grid container">
  <div class="nine wide column">
    <div class="ui fluid card">
      <div class="content">
        <form class="ui form"  method="post">
          {% csrf_token %}
          {% for erro in form.non_field_erros %}
            <div class="ui red message">
              {{error}}
            </div>
          {% endfor %}

          <div class="field">
            <label for="{{form.username.auto_id}}">{{form.username.label}}</label>
            <div class="ui left icon input">
              {% render_field form.username placeholder="fulano" %}
              <i class="user icon"></i>
            </div>
            {% for error in form.username.errors %}
              <div class="ui error message">
                <div class="header">
                  Atenção!
                </div>
                <p>{{error}}</p>
              </div>
            {% endfor %}
          </div>

          <div class="field">
            <label for="{{form.password.auto_id}}">{{form.password.label}}</label>
            <div class="ui left icon input">
                {% render_field form.password placeholder="senha" %}
                <i class="lock icon"></i>
            </div>

            {% for error in form.password.errors %}
              <div class="ui error message">
                <div class="header">
                  Atenção!
                </div>
                <p>{{error}}</p>
              </div>

            {% endfor %}
          </div>

          <button type="submit" class="ui animated blue right floated submit button" name="button">
            <div class="visible content">Entrar</div>
            <div class="hidden content">
              <i class="sign in icon"></i>
            </div>
          </button>

        </form>
      </div>

      <div class="content">
        <div class="ui center aligned">
          <a class="ui secondary labeled icon button" href="{% url 'accounts:signin' %}" tabindex="0">
            Registrar-se
            <i class="add user icon"></i>
          </a>

        </div>

      </div>

    </div>
  </div>

</div>
</main>
{% endblock %}

accounts/templates/new.html
{% extends 'imports.html' %}

{% load widget_tweaks %}
{% block 'nav' %}
<main>

<div class="nine wide column">
  <div class="ui fluid card">
    <div class="content">
      <form class="ui form" method="post">
        {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="ui red message">{{error}}</div>
            {% endfor %}

            <div class="field">
              <label for="{{form.username.auto_id}}" >{{form.username.label}}</label>
              <div class="ui left icon input">
                {% render_field form.username %}
                <i class="user icon"></i>
              </div>
              {% for error in form.username.errors %}

              <div class="ui error message">
                <div class="header">Atenção!</div>
                <p>{{error}}</p>
              </div>
              {% endfor %}

            </div>

            <div class="field">
              <label for="{{form.email.auto_id}}" >{{form.email.label}}</label>
              <div class="ui left icon input">
                {% render_field form.email %}
                <i class="mail icon"></i>
              </div>
              {% for error in form.email.errors %}

              <div class="ui error message">
                <div class="header">Atenção!</div>
                <p>{{error}}</p>
              </div>
              {% endfor %}
          </div>



            <div class="field">
            <label for="{{form.password1.auto_od}}">{{form.password1.label}}</label>
              <div class="ui left icon input">
                <i class="lock icon"></i>
                {% render_field form.password1 %}
              </div>
              {% for error in form.password1.errors %}

              <div class="ui error message">
                <div class="header">Atenção!</div>
                <p>{{error}}</p>
              </div>
              {% endfor %}
            </div>



            <div class="field">
              <label for="{{form.password2.auto_od}}">{{form.password2.label}}</label>
              <div class="ui left icon input">
                <i class="lock icon"></i>
                {% render_field form.password2 %}
              </div>

              {% for error in form.password2.errors %}
              <div class="ui error message">
                <div class="header">Atenção!</div>
                <p>{{error}}</p>
              </div>
              {% endfor %}

            </div>



            <div class="ui error message"></div>
            <button type="submit" class="ui animated primary right floated submit button" tabindex="0">
              <div class="visible content">Registrar</div>
              <div class="hidden content">
                <i class="add user icon"></i>
              </div>

            </button>

        </form>
        </div>
      </div>
    </div>
  </div>
</main>
  {% endblock %}

accounts/templates/profile.html
{% extends 'nav.html' %}
{% load widget_tweaks %}
{% load static %}

{% block 'content' %}

<div class="ui segments">
  <header class="ui clearing segment">
    <a href="{% url 'accounts:edit_profile' %}" class="ui right floated yellow button">
  Editar perfil
    </a>
    <a class="ui right floated teal button">
  Meus Tópicos
    </a>
  </header>

<div class="ui segment">
    <div class="ui large feed">
      <div class="label">
        {% with 'imgs/avatars/'|add:user.avatar|add:'.png' as avatar %}
        <img src="{% static avatar %}">
        {% endwith %}
</div>

      <h1>Nome ou usuário: {{user}}</h1>
      <h2>Email: {{user.email}}</h2>
    </div>
<div>
</div>

{% endblock %}