accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views

urlpatterns = [
    url(r'^login/$', login, {'template_name':'login.html'},name='login'),
    url(r'^logout/$', logout,{'next_page':'accounts:login'}, name='logout'),
    url(r'^signin/$', views.signin, name = 'signin'),
    url(r'^profile/$',views.profile,name='profile'),
    url(r'^edit/profile$',views.edit_profile,name='edit_profile'),
]

forum/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.list_topic, name='feed'),
    url(r'^ask/',views.create_topic,name='ask'),
    url(r'detail/(?P<pk>\d+)',views.detail_topic, name='detail'),
    url(r'^answers/(?P<pk>\d+)/correct',views.reply_correct,name='reply_correct'),
    url(r'^answers/(?P<pk>\d+)/incorrect',views.reply_incorrect,name='reply_incorrect'),
]

olimpo_andressa/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^accounts/', include('accounts.urls',namespace='accounts')),
    url(r'^',include('forum.urls', namespace='forum')),
    url(r'^admin/', admin.site.urls),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

# Create your views here.

core/templates/imports.html
<!DOCTYPE html>
 {% load static %}
<html lang='pt-br'>
  <head>
    <meta charset="utf-8">
    <title>Olimpo - Andressa</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'vendors/semantic/semantic.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
  </head>
  <body>
{% block 'nav' %}

{% endblock %}

  <script type="text/javascript" src="{% static 'vendors/jquery/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'vendors/semantic/semantic.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>

  </body>
</html>

core/templates/nav.html
{% extends "imports.html" %}

{% block 'nav' %}
  <main>
    <div class="ui container">
      <div class="ui pointing menu">

        <a class="item
        {% if request.resolver_match.url_name == 'feed' %} active {% endif %}
        " href="{% url 'forum:feed' %}">
          <i class="feed icon"></i>Feed
        </a>
        <a class="item
        {% if request.resolver_match.url_name == 'ask' %} active {% endif %}
        " href="{% url 'forum:ask' %}">
          <i class="comment icon"></i>Perguntar
        </a>

        <div class="right menu">
          <div class="item">
            <div class="ui transparent icon input">
                <form  action="#" method="post">

                  <div class="ui action input">
                    <input type="text" name="search" value="" placeholder="Pesquisar">
                    <button class="ui icon button" type="submit" name="button">
                      <i class="search icon"></i>
                    </button>

                  </div>

                </form>
            </div>
          </div>
          {% if user.is_authenticated %}
          <a class="item" href="{% url 'accounts:profile' %}">
            <i class="user icon"></i> {{user}}
          </a>

          <a class="item" href="{% url 'accounts:logout' %}">
            <i class="sign out icon"></i> Sair
          </a>
         {% else %}

          <a class="item" href="{% url 'accounts:login' %}">
            <i class="sign in icon"></i> Login
          </a>
          {% endif %}
        </div>
      </div>
      {% block 'content' %}

      {% endblock %}

    </div>
  </main>
{% endblock %}